import type { NextPage } from "next";
import Head from "next/head";
import { order, restock } from "../features/cake/cakeSlice";
import {
  order as orderIcecream,
  restock as restockIcecream,
} from "../features/icecream/icecreamSlice";
import type { RootState } from "../app/store";
import { useAppDispatch, useAppSelector } from "../app/hooks";

const selectValue = (state: RootState) => [
  state.cake.numberOfCakes,
  state.icecream.numberOfIcecreams,
];

const Home: NextPage = () => {
  const [numberOfCakes, numberOfIcecreams] = useAppSelector(selectValue);
  const dispatch = useAppDispatch();

  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center gap-8">
        <div className="flex flex-col w-56 gap-4">
          <h1> Stock of cakes - {numberOfCakes} </h1>
          <button
            onClick={() => dispatch(order())}
            className="w-full h-10 bg-green-400/50"
          >
            Order Cake
          </button>
          <button
            onClick={() => dispatch(restock())}
            className="w-full h-10 bg-green-400/50"
          >
            Restock Cake
          </button>
        </div>

        <div className="flex flex-col w-56 gap-4">
          <h1> Stock of icecreams - {numberOfIcecreams} </h1>
          <button
            onClick={() => dispatch(orderIcecream())}
            className="w-full h-10 bg-green-400/50"
          >
            Order Icecream
          </button>
          <button
            onClick={() => dispatch(restockIcecream())}
            className="w-full h-10 bg-green-400/50"
          >
            Restock Icecream
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
