import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="flex justify-center items-center p-8">
      <Head>
        <title>Progressivo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="mb-2 text-2xl sm:text-3xl md:text-3xl font-semibold text-green-300 border-b-2 border-b-green-200 tracking-wide">
          Progress with Progressivo
        </h1>
        <ul className="text-md italic text-blue-300 list-disc ml-6">
          <li>Create a board for a new project.</li>
          <li>
            Add state defining columns to the board and add new tasks to the
            columns when required
          </li>

          <li>
            Move the tasks between different columns according to your progress
            using drag and drop
          </li>
          <li>
            If needed use drag and drop to reorder the boards and columns also
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Home;
