import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import { order, restock } from "../features/cake/cakeSlice";
import {
  order as orderIcecream,
  restock as restockIcecream,
} from "../features/icecream/icecreamSlice";
import type { RootState } from "../app/store";
import { useAppDispatch, useAppSelector } from "../app/hooks";
import Image from "next/image";
import { FaBars } from "react-icons/fa";
import { useEffect, useState } from "react";
// import { BoardsSummary } from "../features/boards/BoardsSummary";
import { DragDropContext, DropResult } from "react-beautiful-dnd";
import { onBoardDragAndDrop } from "../features/boards/boardsSlice";
import { Boards } from "../types/types";
import { AppLayout } from "../components/AppLayout";

const BoardsSummary = dynamic(
  () => import("../features/boards/BoardsSummary"),
  { ssr: false }
);

const selectValue = (state: RootState) => [];

const Home: NextPage = () => {
  const [numberOfCakes, numberOfIcecreams] = useAppSelector(selectValue);
  const boards = useAppSelector((state) => state.boards);
  const dispatch = useAppDispatch();
  const [open, setOpen] = useState(false);

  const handleSideNavigationBar = () => {
    setOpen((prev) => !prev);
  };

  return (
    <div>
      <Head>
        <title>Progressivo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AppLayout> */}
      <div className="max-w-md flex flex-col gap-4">
        <h1 className="text-2xl sm:text-3xl md:text-4xl font-semibold text-green-300 border-b-2 border-b-green-200">
          Welcome to Progressivo
        </h1>
        <ul className="text-md italic text-blue-300 list-disc ml-6">
          <li>Break a project or a work into tasks</li>

          <li>Add new task or remove when needed</li>

          <li>
            Move the tasks to different lifecycle states using drag and drop
          </li>
          <li>
            And let&apos;s select a board from the left bar and start progress
            with Progressivo
          </li>
        </ul>
      </div>
      {/* </AppLayout> */}
    </div>
  );
};

export default Home;
